/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/rolex/rolex.glb --transform
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {useFrame, useThree} from "@react-three/fiber";
import {toScreenPosition} from "../SceneUtils";
import InteractivePart from "./InteractivePart";

export function Model(props) {
    const {nodes, materials} = useGLTF('/rolex/rolex-transformed.glb')

    const detailPoint1Ref = useRef()
    const detailPoint2Ref = useRef()

    const {gl} = useThree()

    useFrame((state) => {

        const positions = [
            toScreenPosition(detailPoint1Ref.current, state.camera, gl),
            toScreenPosition(detailPoint2Ref.current, state.camera, gl)
        ]

        props.setDetailPointPositions(positions)
    })

    return (
        <group {...props} dispose={null}>
            <group>

                <mesh position={[1, 2, 1]} ref={detailPoint1Ref}/>
                <mesh position={[1, 4, 0]} ref={detailPoint2Ref}/>

                <group position={[1.03, 2.78, 0.14]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}>

                    {/*part bezel*/}
                    <InteractivePart
                        onClick={() => props.setUnderlayTopic('bezel')}
                        geometry={nodes.Circle008_1.geometry}
                        material={materials['Material.003']}
                    />

                    <mesh geometry={nodes.Circle008_2.geometry}
                          material={materials['glossy black']}
                    />
                </group>

                {/*part latch*/}
                <InteractivePart
                    onClick={() => props.setUnderlayTopic('latch')}
                    geometry={nodes.Plane008.geometry}
                    material={materials.meetal}
                    position={[-2.18, 2.06, 0.14]}
                    rotation={[Math.PI / 2, 0.24, -Math.PI / 2]}/>

                {/*part tension head*/}
                <InteractivePart
                    onClick={() => props.setUnderlayTopic('crown')}
                    geometry={nodes.Circle010.geometry}
                    material={materials.meetal}
                    // material={new THREE.MeshStandardMaterial({color: 0xff0000})}
                    position={[0.8, 2.75, -1.33]}
                    rotation={[Math.PI / 2, 0.25, Math.PI]} scale={0.2}/>


                <mesh geometry={nodes.Circle.geometry}
                      material={materials.meetal}
                      position={[1.03, 2.78, 0.14]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>
                <mesh geometry={nodes.Circle001.geometry} material={materials.meetal} position={[1.03, 2.78, 0.14]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>
                <mesh geometry={nodes.Circle002.geometry} material={materials.meetal} position={[1.03, 2.78, 0.14]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>
                <mesh geometry={nodes.Circle003.geometry} material={materials.meetal}
                      position={[0.89, 3.48, -0.29]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle004.geometry} material={materials['meetal.001']}
                      position={[0.58, 2.69, 0.14]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={1.29}/>
                <mesh geometry={nodes.Circle005.geometry} material={materials.chrome} position={[0.56, 2.68, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[1.1, 1, 1.1]}/>

                <mesh geometry={nodes.Circle006.geometry}
                      material={materials['meetal.002']}
                      position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]}/>


                <mesh geometry={nodes.Circle008.geometry} material={materials['glossy black.001']}
                      position={[1.06, 2.79, 0.14]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>
                <mesh geometry={nodes.Circle009.geometry} material={materials.glass} position={[1.03, 2.78, 0.14]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>


                <group position={[0.88, 4.02, 0.14]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]}>
                    <mesh geometry={nodes.Circle013_1.geometry} material={materials.meetal}/>
                    <mesh geometry={nodes.Circle013_2.geometry} material={materials['Material.002']}/>
                </group>
                <mesh geometry={nodes.Circle012.geometry} material={materials['Material.002']}
                      position={[0.89, 3.48, -0.29]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.08}/>
                <mesh geometry={nodes.Circle014.geometry} material={materials['Material.002']}
                      position={[0.97, 3.19, -0.58]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle016.geometry} material={materials['Material.002']}
                      position={[1.18, 2.38, -0.58]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle018.geometry} material={materials['Material.002']}
                      position={[1.25, 2.08, -0.28]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle020.geometry} material={materials['Material.002']}
                      position={[0.89, 3.48, 0.55]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.08}/>
                <mesh geometry={nodes.Circle022.geometry} material={materials['Material.002']}
                      position={[0.97, 3.19, 0.85]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle024.geometry} material={materials['Material.002']}
                      position={[1.18, 2.38, 0.85]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle026.geometry} material={materials['Material.002']}
                      position={[1.25, 2.08, 0.55]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle013.geometry} material={materials.meetal}
                      position={[0.97, 3.19, -0.58]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle015.geometry} material={materials.meetal}
                      position={[1.18, 2.38, -0.58]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle017.geometry} material={materials.meetal}
                      position={[1.25, 2.08, -0.28]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.07}/>
                <mesh geometry={nodes.Circle019.geometry} material={materials.meetal} position={[0.89, 3.48, 0.55]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle021.geometry} material={materials.meetal} position={[0.97, 3.19, 0.85]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle023.geometry} material={materials.meetal} position={[1.18, 2.38, 0.85]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle025.geometry} material={materials.meetal} position={[1.25, 2.08, 0.55]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={-0.07}/>
                <mesh geometry={nodes.Circle027.geometry} material={materials['Material.001']}
                      position={[1.06, 2.79, 0.14]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}/>
                <group position={[1.13, 2.82, 0.15]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.05}>
                    <mesh geometry={nodes.Circle042.geometry} material={materials.meetal}/>
                    <mesh geometry={nodes.Circle042_1.geometry} material={materials['Material.002']}/>
                </group>
                <group position={[1.13, 2.82, 0.15]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.05}>
                    <mesh geometry={nodes.Circle043.geometry} material={materials.meetal}/>
                    <mesh geometry={nodes.Circle043_1.geometry} material={materials['Material.002']}/>
                </group>
                <group position={[1.13, 2.82, 0.15]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.05}>
                    <mesh geometry={nodes.Circle044.geometry} material={materials.meetal}/>
                    <mesh geometry={nodes.Circle044_1.geometry} material={materials['Material.002']}/>
                </group>
                <mesh geometry={nodes.Circle031.geometry} material={materials.chrome}
                      position={[-0.16, 4.6, -0.48]}
                      rotation={[-Math.PI / 2, 1.09, 0]} scale={[0.83, 0.93, 0.83]}/>
                <mesh geometry={nodes.Circle032.geometry} material={materials.chrome} position={[-0.16, 4.6, 0.75]}
                      rotation={[Math.PI / 2, -1.09, Math.PI]} scale={[-0.83, -0.93, -0.83]}/>
                <mesh geometry={nodes.crown.geometry} material={materials.meetal} position={[-2.08, 1.22, 0.14]}
                      rotation={[-Math.PI / 2, -0.47, -Math.PI / 2]} scale={[7.13, 3.8, 7.13]}/>
                <mesh geometry={nodes.crown001.geometry} material={materials.meetal} position={[0.79, 2.8, -1.58]}
                      rotation={[-1.59, -0.3, -0.01]} scale={-4.15}/>
                <mesh geometry={nodes.Cube.geometry} material={materials.meetal} position={[0.82, 2.75, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[1.52, 1.67, 1.67]}/>
                <mesh geometry={nodes.Cube001.geometry} material={materials.meetal} position={[0.82, 2.75, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[1.52, 1.67, 1.67]}/>
                <mesh geometry={nodes.Cube002.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube003.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube004.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]}/>
                <mesh geometry={nodes.Cube005.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube006.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube007.geometry} material={materials.meetal} position={[0.58, 2.67, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube008.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube009.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube010.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube011.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube012.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube013.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube014.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube016.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube019.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cube020.geometry} material={materials.meetal} position={[0.57, 2.69, 0.14]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.12, 0.19, 0.12]}/>
                <mesh geometry={nodes.Cylinder.geometry} material={materials.meetal} position={[1.11, 2.82, 0.15]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={-0.02}/>

                <mesh
                    geometry={nodes.Plane001.geometry}
                    material={materials.meetal}
                    position={[-2.18, 2.06, 0.14]}
                    rotation={[Math.PI / 2, 0.24, -Math.PI / 2]}/>

                <mesh
                    geometry={nodes.Plane002.geometry}
                    material={materials.meetal}
                    position={[-1.82, 1.59, 0.13]}
                    rotation={[Math.PI / 2, 0.46, -Math.PI / 2]}
                    scale={[0.58, 1, 1]}/>

                <mesh geometry={nodes.Plane003.geometry} material={materials.meetal}
                      position={[-1.82, 1.59, 0.13]} rotation={[Math.PI / 2, 0.46, -Math.PI / 2]} scale={[0.58, 1, 1]}/>
                <mesh geometry={nodes.Plane004.geometry} material={materials.meetal} position={[-1.82, 1.59, 0.13]}
                      rotation={[Math.PI / 2, 0.46, -Math.PI / 2]} scale={[0.58, 1, 1]}/>
                <mesh geometry={nodes.Plane005.geometry} material={materials['Material.002']}
                      position={[0.85, 3.65, 0.12]} rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={0.03}/>
                <mesh geometry={nodes.Plane006.geometry} material={materials.meetal} position={[0.85, 3.65, 0.12]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[0.91, 0.8, 0.8]}/>
                <mesh geometry={nodes.Plane007.geometry} material={materials['glass.001']}
                      position={[1.2, 2.81, -0.54]}
                      rotation={[Math.PI / 2, 0.25, -Math.PI / 2]} scale={[-0.18, -0.25, -0.2]}/>

                <mesh geometry={nodes.Plane009.geometry} material={materials['Material.002']}
                      position={[1.08, 2.78, 0.88]} rotation={[-Math.PI / 2, -0.25, Math.PI / 2]}
                      scale={[-0.14, -0.14, -0.05]}/>
                <mesh geometry={nodes.Plane011.geometry} material={materials['Material.002']}
                      position={[1.26, 2.06, 0.14]} rotation={[Math.PI, 0, 1.32]} scale={[-0.14, -0.14, -0.04]}/>
                <mesh geometry={nodes.Plane010.geometry} material={materials.meetal} position={[1.07, 2.78, 0.88]}
                      rotation={[-Math.PI / 2, -0.25, Math.PI / 2]} scale={[-1.09, -1.09, -1.08]}/>
                <mesh geometry={nodes.Plane012.geometry} material={materials.meetal} position={[1.26, 2.06, 0.14]}
                      rotation={[-Math.PI, 0, 1.32]} scale={[-1.09, -1.09, -0.91]}/>
            </group>
        </group>
    )
}


useGLTF.preload('/rolex-transformed.glb')

export default Model;
